### PR TITLE
Adjusted some formatting to make easier to read (using bullet points etc) + misc typo/grammar fixes

### PR DESCRIPTION
**Pull request by hi2u**
Thought it might be worth breaking up some of the larger paragraphs into bullet points and stuff like that.  And a few other minor misc fixes.

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
Thank you very much for your time. Sadly I don't have write access to this repository anymore :( It belongs to my former employer and I can't merge it.

**Comment by uweschaefer** [comment]
@donaldpipowitch did you ask for write access? i cannot imagine anyone rejecting it at mercateo.

**Comment by donaldpipowitch** [comment]
Not yet. I'll do it in the next days.

**Comment by donaldpipowitch** [comment]
🥳

**Pull request merged**
